---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
files: ^(anta|scripts|tests)/

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-merge-conflict

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: Check for changes when running isort on all python files

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        name: Check for changes when running Black on all python files

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        name: Check for PEP8 error on Python files
        args:
          - --config=/dev/null
          - --max-line-length=165

  - repo: local  # as per https://pylint.pycqa.org/en/latest/user_guide/installation/pre-commit-integration.html
    hooks:
      - id: pylint
        entry: pylint
        language: python
        name: Check for Linting error on Python files
        description: This hook runs pylint.
        types: [python]
        args:
          - -rn                # Only display messages
          - -sn                # Don't display the score
          - --rcfile=pylintrc  # Link to config file

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.4.1
    hooks:
      - id: mypy
        args:
          - --config-file=pyproject.toml
        additional_dependencies:
          - "aio-eapi==0.3.0"
          - "click==8.1.3"
          - "click-help-colors==0.9.1"
          - "cvprac~=1.3"
          - "netaddr==0.8.0"
          - "pydantic~=2.0"
          - "PyYAML==6.0"
          - "requests>=2.27"
          - "rich~=13.4"
          - "asyncssh==2.13.1"
          - "Jinja2==3.1.2"
          - types-PyYAML
          - types-paramiko
          - types-requests
        files: ^(anta|tests)/
