name: Mkdocs
on:
  push:
    branches:
      - main
jobs:
  'build_doc':
    name: 'Update Public documentation'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: 'Setup Python 3 on runner'
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: 'Build mkdocs content to site folder'
        run: |
            pip install -r ./docs/requirements.txt
            mike deploy --push devel
